version: 2

project_name: prt

before:
  hooks:
    - go vet ./...
    - go test -race ./...
    - go test ./...

builds:
  - id: prt
    main: ./cmd/prt
    binary: prt
    ldflags:
      - -s -w -X github.com/nitoba/pr-tools/apps/cli-go/internal/version.Version={{ .Version }} -X github.com/nitoba/pr-tools/apps/cli-go/internal/version.Commit={{ .Commit }} -X github.com/nitoba/pr-tools/apps/cli-go/internal/version.Date={{ .Date }}
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]

archives:
  - id: prt-archives
    builds: [prt]
    name_template: "prt_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: prt_{{ .Version }}_checksums.txt

release:
  disable: false
